### ISSUE TITLE
Use `spok` for deepEqual testing

### ISSUE THREAD

**Issue by ajoslin** [chrisinajar/crispum#1]
```js
require('tape')('a == b', () => {
  require('spok')(t, {}, {}) // gives detailed key-by-key errors
})
```

I still follow you on github and I saw your library, then I read your tests, then I was like "spok would be good here". So I opened an issue.

**Comment by chrisinajar** [comment]
I used this in another project that has a TON of data entry and much of it is derived from other values and it's life saving :+1:
